#!/usr/bin/env bash

  #-device ioh3420,bus=pcie.0,addr=1c.0,multifunction=on,port=1,chassis=1,id=root.1 \
  #-device vfio-pci,host=01:00.0,bus=root.1,addr=00.0,x-pci-sub-device-id=1800,x-pci-sub-vendor-id=4136,multifunction=on,romfile=/home/leo60228/.MyGPU.rom \
  #-vga none \
  #-nographic \

qemu-system-x86_64 \
  -name "WindowsServer-QEMU" \
  -machine type=q35,accel=kvm \
  -cpu host,kvm=off,hv_vapic,hv_relaxed,hv_spinlocks=0x1fff,hv_time,hv_vendor_id=12alphanum \
  -smp 8,sockets=1,cores=4,threads=2 \
  -m 8G \
  -balloon none \
  -rtc clock=host,base=localtime \
  -vnc 127.0.0.1:1 \
  -device qxl,bus=pcie.0,addr=1c.2 \
  -serial none \
  -parallel none \
  -k en-us \
  -usb -usbdevice tablet \
  -cdrom /home/leo60228/Documents/Downloads/en_windows_server_2016_updated_feb_2018_x64_dvd_11636692.iso \
  -drive file=/dev/sda,if=virtio,format=raw \
  -drive file=virtio-win.iso,format=raw,media=cdrom,index=1 \
  -boot menu=on \
  -netdev type=tap,id=net0,ifname=tap0,script=tap_ifup,downscript=tap_ifdown,vhost=on \
  -device virtio-net-pci,netdev=net0,addr=19.0,mac=52:54:BE:EF:A8:A5
