# This file was generated by pkgs.mastodon.updateScript.
{ fetchgit, applyPatches }: let
  src = fetchgit {
    url = "https://github.com/leo60228/mastodon.git";
    rev = "d1255ab8a5101bc04af4a5214f975edf443a37d9";
    sha256 = "1qkfcc82h6ybi9xpjizr329i2diiprv2s6rk4bmbbaz14b3w0fwm";
  };
in applyPatches {
  inherit src;
  patches = [../files/mastodon-custom-poll-option-limits.patch ../files/mastodon-discord.patch ../files/mastodon-kind-of-deps.patch ./version.patch ];
}
