# This file was generated by pkgs.mastodon.updateScript.
{ fetchgit, applyPatches }: let
  src = fetchgit {
    url = "https://github.com/glitch-soc/mastodon.git";
    rev = "7632255115a7f6e6f9f8047f0d0d1b90d7ee9315";
    sha256 = "01jydwkzjwm4xcv9q8ssd98x68zwighi8m2kyqnb28jirpwqmqs2";
  };
in applyPatches {
  inherit src;
  patches = [../files/mastodon-discord.patch ../files/mastodon-internal-names.patch ../files/mastodon-kind-of-deps.patch ./version.patch ];
}
