{ branch ? "canary", pkgs, base ? ./discord-base.nix, deviceScaleFactor ? 1 }:
# Generated by /maintainers/scripts/update-discord
let
  inherit (pkgs) callPackage fetchurl;
in {
  stable = callPackage base rec {
    inherit deviceScaleFactor;
    pname = "discord";
    binaryName = "Discord";
    desktopName = "Discord";
    version = "0.0.17";
    src = fetchurl {
      url = "https://dl.discordapp.net/apps/linux/${version}/discord-${version}.tar.gz";
      sha256 = "058k0cmbm4y572jqw83bayb2zzl2fw2aaz0zj1gvg6sxblp76qil";
    };
  };
  canary = callPackage base rec {
    inherit deviceScaleFactor;
    pname = "discord-canary";
    binaryName = "DiscordCanary";
    desktopName = "Discord Canary";
    version = "0.0.135";
    src = fetchurl {
      url = "https://dl-canary.discordapp.net/apps/linux/${version}/discord-canary-${version}.tar.gz";
      sha256 = "19ri82pwz43wma9kyy2109wdbrmq2zxy2bq03l3i7m4j2pfbwqbn";
    };
  };
}.${branch}
