{ callPackage, darwin, qt5 }:
# Generated by /maintainers/scripts/update-dolphin
{
  beta = qt5.callPackage ./dolphin-base.nix rec {
    inherit (darwin.apple_sdk.frameworks) CoreBluetooth ForceFeedback IOKit OpenGL;
    version = "5.0-11824";
    rev = "1b97f081b8eff9012132a4124537968bdb0e03e0";
    sha256 = "1v96hcn34040vjsw83k8p0r0nb8rrdcz80h4ngirxzm36b3l7w6m";
    branch = "beta";
  };
  dev = qt5.callPackage ./dolphin-base.nix rec {
    inherit (darwin.apple_sdk.frameworks) CoreBluetooth ForceFeedback IOKit OpenGL;
    version = "5.0-11830";
    rev = "960ba4fe5e243056c3ef8a71f5298dc48722d29c";
    sha256 = "0r8gyrlyar2xcqbmvrv7mp1jbiyn38azh1zksx4088qxc5kpa273";
    branch = "dev";
  };
}
