{ callPackage, darwin, qt5 }:
# Generated by /maintainers/scripts/update-dolphin
{
  beta = qt5.callPackage ./dolphin-base.nix rec {
    inherit (darwin.apple_sdk.frameworks) CoreBluetooth ForceFeedback IOKit OpenGL;
    version = "5.0-12247";
    rev = "9c12a843f86d39bc64d9e9b5b670e67455487739";
    sha256 = "1lqbylyzlkyzdmv7ydi96z6xqm4blpl5sa7bj0g4va0l6gv4qxfx";
    branch = "beta";
  };
  dev = qt5.callPackage ./dolphin-base.nix rec {
    inherit (darwin.apple_sdk.frameworks) CoreBluetooth ForceFeedback IOKit OpenGL;
    version = "5.0-12380";
    rev = "afd25de85ef836ca376d84062e48674d2a5218d9";
    sha256 = "0s2qpq0rci74j7jfw2yjhwrm8wx65wixcy8wj51x9dc25dfd901r";
    branch = "dev";
  };
}
