[common]
v4 = "10.100.0.0"

[networks.mesh]
v4 = "10.100.0.0"

[hosts.prometheus]
network = "mesh"
ip_addr = "68.183.115.15"

[hosts.prometheus.wireguard]
pubkey = "R19IME8fMBp2/FOKzEWnECn1yMyWjPsZNXaD6q0jTTc="
port = 51820
addrs = { v4 = "10.100.0.1" }

[hosts.desktop]
network = "mesh"

[hosts.desktop.wireguard]
pubkey = "9uXlgMZ+L53g8ljJwSyeudC21tQw9STuT7Uolyr6fXM="
port = 51820
addrs = { v4 = "10.100.0.2" }
