{ branch ? "canary", pkgs, base ? ./discord-base.nix, deviceScaleFactor ? 1 }:
# Generated by /maintainers/scripts/update-discord
let
  inherit (pkgs) callPackage fetchurl;
in {
  stable = callPackage base rec {
    inherit deviceScaleFactor;
    pname = "discord";
    binaryName = "Discord";
    desktopName = "Discord";
    version = "0.0.20";
    src = fetchurl {
      url = "https://dl.discordapp.net/apps/linux/${version}/discord-${version}.tar.gz";
      sha256 = "1355xiw0k0i6cbi1zcq7fphma6r8hz87lhm8ybg5s45032xz5znx";
    };
  };
  canary = callPackage base rec {
    inherit deviceScaleFactor;
    pname = "discord-canary";
    binaryName = "DiscordCanary";
    desktopName = "Discord Canary";
    version = "0.0.140";
    src = fetchurl {
      url = "https://dl-canary.discordapp.net/apps/linux/${version}/discord-canary-${version}.tar.gz";
      sha256 = "1k88f7nychz5bz1c02mca29bm7a6z4ymc6sq8ly9wf0y0f8f6ih0";
    };
  };
}.${branch}
