{ branch ? "canary", pkgs, base ? ./discord-base.nix, deviceScaleFactor ? 1 }:
# Generated by /maintainers/scripts/update-discord
let
  inherit (pkgs) callPackage fetchurl;
in {
  stable = callPackage base rec {
    inherit deviceScaleFactor;
    pname = "discord";
    binaryName = "Discord";
    desktopName = "Discord";
    version = "0.0.21";
    src = fetchurl {
      url = "https://dl.discordapp.net/apps/linux/${version}/discord-${version}.tar.gz";
      sha256 = "18rmw979vg8lxxvagji6sim2s5yyfq91lfabsz1wzbniqfr98ci8";
    };
  };
  canary = callPackage base rec {
    inherit deviceScaleFactor;
    pname = "discord-canary";
    binaryName = "DiscordCanary";
    desktopName = "Discord Canary";
    version = "0.0.143";
    src = fetchurl {
      url = "https://dl-canary.discordapp.net/apps/linux/${version}/discord-canary-${version}.tar.gz";
      sha256 = "0nhnsvkdz2xn1ykszkmjrjs7lkdbwqj402bygqhgh0lks61v5v1b";
    };
  };
}.${branch}
