#!/bin/sh

RSET=/
HSET=/host.slice
HNODE=N0
MSET=/machine.slice
MNODE=N1

disable_isolation () {
    vfio-isolate \
        cpuset-delete $HSET \
        cpuset-delete $MSET
}

enable_isolation () {
    vfio-isolate \
        drop-caches \
        compact-memory \
        cpuset-create --cpus $HNODE --mems $HNODE -mm $HSET \
        cpuset-create --cpus $MNODE --mems $MNODE -ce -me -mm $MSET \
        move-tasks $RSET $HSET
}

case "$2" in
"prepare")
    enable_isolation
    ;;
"release")
    disable_isolation
    ;;
esac
