{ neovim, tree-sitter, python3, vimPlugins, omnisharp-roslyn, callPackage, lib }:
let ftPlugins = with vimPlugins; [
        { plug = callPackage ./graphql.nix {}; ft = "graphql"; ext = "graphql"; }
        { plug = callPackage ./omnisharp-vim.nix {}; ft = "cs"; ext = "cs"; }
        { plug = vim-qml; ft = "qml"; ext = "qml"; set = "smartindent"; }
        { plug = vim-toml; ft = "toml"; ext = "toml"; }
        { plug = vim-terraform; ft = "terraform"; ext = "tf"; }
    ];
    plugins = builtins.attrNames (builtins.readDir ./vimrc.d);
in neovim.override {
    vimAlias = true;

    configure = {
        customRC = builtins.readFile ./vimrc
            + "\" LSP paths (autogenerated) {{{\n"
            + "let g:OmniSharp_server_path = '${omnisharp-roslyn}/bin/omnisharp'\n"
            + "\" }}}"
            + "\n\" Filetype plugins (autogenerated) {{{\n"
            + lib.concatMapStrings (x:
                "autocmd BufRead,BufNewFile *.${x.ext} packadd ${x.plug.pname} | set filetype=${x.ft}\n" +
                "autocmd FileType ${x.ft} packadd ${x.plug.pname}\n" +
                (if x ? set then "autocmd FileType ${x.ft} set ${x.set}\n" else "")
            ) ftPlugins
            + "\" }}}\n\n\" vimrc.d/ contents:\n\n" + lib.concatMapStrings (x:
                "\" ${x}\n${(builtins.readFile (./vimrc.d + "/${x}"))}\n\n"
            ) plugins;

        packages.leovim = with vimPlugins; {
            start = [
                vim-hardtime
                editorconfig-vim
                vim-sleuth
                (callPackage ./ale.nix {})
                (callPackage ./nvim-treesitter.nix {
                    grammars = {
                        inherit (tree-sitter.builtGrammars) tree-sitter-nix tree-sitter-javascript tree-sitter-html tree-sitter-regex tree-sitter-pioasm;
                    };
                })
                (callPackage ./playground.nix {})
                (callPackage ./nvim-treesitter-refactor.nix {})
                vim-auto-save
            ];

            opt = [
                (callPackage ./solarized8.nix {})
                (callPackage ./vimspector.nix {})
            ]
                ++ map (x: x.plug) ftPlugins;
        };
    };
}
