# This file was generated by pkgs.mastodon.updateScript.
{
  stdenv,
  fetchFromGitHub,
  applyPatches,
  patches ? [ ],
}:
let
  version = "unstable-2025-04-06";
in
(applyPatches {
  src = fetchFromGitHub {
    owner = "BlaseballCrabs";
    repo = "mastodon";
    rev = "d6ca3fd2345369a45c1ee3a232b10fb1cba85079";
    hash = "sha256-GeQ5sJ7Yx3IC5wNha66UmZMFEyYGWLtIbJZWEqInUB0=";
  };
  patches = patches ++ [ ];
})
// {
  inherit version;
  yarnHash =
    if stdenv.isAarch64 then
      "sha256-1tH4+z2llY69G1AdLmQjeRYlVfL1zZ3QJArLCId2xRY="
    else
      "sha256-5FqQ6jYjDeu/jCzwsA08JPADmi+BKSk+pv2VqREwGUE=";
}
