# This file was generated by pkgs.mastodon.updateScript.
{
  fetchFromGitHub,
  applyPatches,
  patches ? [ ],
}:
let
  version = "unstable-2026-09-04";
in
applyPatches {
  src = fetchFromGitHub {
    owner = "BlaseballCrabs";
    repo = "mastodon";
    rev = "d9000b3fe307c2d24b364d6c1687e870fa5ff777";
    hash = "sha256-1NAynKWaXdXe1P59h4vOaMC0TEzSGX1mn4R1IkQzNZw=";
    passthru = {
      inherit version;
      yarnHash = "sha256-xJ13bSBARpDP/RWWQwnJji6+YPrTbmm49G7di4olLwk=";
      yarnMissingHashes = ./missing-hashes.json;
    };
  };
  patches = patches ++ [ ];
}
