# This file was generated by pkgs.mastodon.updateScript.
{ fetchgit, applyPatches }: let
  src = fetchgit {
    url = "https://github.com/BlaseballCrabs/mastodon.git";
    rev = "b5f4946a1f273f5cac7e690fd91f279fc3471f19";
    sha256 = "0wxn1r9wz0gb3xapfm2sc9cylsh6c79zksjfpz4fd9299ivjw0yl";
  };
in applyPatches {
  inherit src;
  patches = [];
}
