# This file was automatically generated by passthru.fetch-deps.
# Please dont edit it manually, your changes might get overwritten!

{ fetchNuGet }:
[
  (fetchNuGet {
    pname = "JetBrains.Annotations";
    version = "2023.3.0";
    sha256 = "0vp4mpn6gfckn8grzjm1jxlbqiq2fglm2rk9wq787adw7rxs8k7w";
  })
  (fetchNuGet {
    pname = "Microsoft.CodeCoverage";
    version = "17.9.0";
    sha256 = "1gljgi69k0fz8vy8bn6xlyxabj6q4vls2zza9wz7ng6ix3irm89r";
  })
  (fetchNuGet {
    pname = "Microsoft.NET.Test.Sdk";
    version = "17.9.0";
    sha256 = "1lls1fly2gr1n9n1xyl9k33l2v4pwfmylyzkq8v4v5ldnwkl1zdb";
  })
  (fetchNuGet {
    pname = "Microsoft.TestPlatform.ObjectModel";
    version = "17.9.0";
    sha256 = "1kgsl9w9fganbm9wvlkqgk0ag9hfi58z88rkfybc6kvg78bx89ca";
  })
  (fetchNuGet {
    pname = "Microsoft.TestPlatform.TestHost";
    version = "17.9.0";
    sha256 = "19ffh31a1jxzn8j69m1vnk5hyfz3dbxmflq77b8x82zybiilh5nl";
  })
  (fetchNuGet {
    pname = "Newtonsoft.Json";
    version = "13.0.1";
    sha256 = "0fijg0w6iwap8gvzyjnndds0q4b8anwxxvik7y8vgq97dram4srb";
  })
  (fetchNuGet {
    pname = "System.Reflection.Metadata";
    version = "1.6.0";
    sha256 = "1wdbavrrkajy7qbdblpbpbalbdl48q3h34cchz24gvdgyrlf15r4";
  })
  (fetchNuGet {
    pname = "xunit.abstractions";
    version = "2.0.3";
    sha256 = "00wl8qksgkxld76fgir3ycc5rjqv1sqds6x8yx40927q5py74gfh";
  })
  (fetchNuGet {
    pname = "xunit.analyzers";
    version = "1.13.0";
    sha256 = "0p9b0b6c9n17ijx8wawzdxf76s6la2y3vrgq6hkrjx4cvx3hdirb";
  })
  (fetchNuGet {
    pname = "xunit.assert.source";
    version = "2.8.0";
    sha256 = "0m1zqb338lfm8ilsm2vdspdhl304wpgwi9zr20d2598mh9y27924";
  })
  (fetchNuGet {
    pname = "xunit.core";
    version = "2.8.0";
    sha256 = "1pnz907fxh8dk529dy0myphv1ahimbqss0lr989nn477yybwsccz";
  })
  (fetchNuGet {
    pname = "xunit.extensibility.core";
    version = "2.8.0";
    sha256 = "1xm8ixvw0vba4npvyzixsqz4f2lnlsw8mz8pvc1zm5f8l30p57nj";
  })
  (fetchNuGet {
    pname = "xunit.extensibility.execution";
    version = "2.8.0";
    sha256 = "0p9qphkqxizzcknsn0p0b6m27ycg5zklzsc2z08pr7bcjp46xxr3";
  })
  (fetchNuGet {
    pname = "xunit.runner.visualstudio";
    version = "2.8.0";
    sha256 = "0rvpv809a0lz2vkw9zicqz6m95h4kkjm4fplh3jfyc7kxl8cm755";
  })
]
