# This file was automatically generated by passthru.fetch-deps.
# Please dont edit it manually, your changes might get overwritten!

{ fetchNuGet }: [
  (fetchNuGet { pname = "JetBrains.Annotations"; version = "2023.3.0"; hash = "sha256-/Eykez68qYMO5mlmUelzAke8aJehyp8fspO5Z+yt5G4="; })
  (fetchNuGet { pname = "Microsoft.CodeCoverage"; version = "17.9.0"; hash = "sha256-OaGa4+jRPHs+T+p/oekm2Miluqfd2IX8Rt+BmUx8kr4="; })
  (fetchNuGet { pname = "Microsoft.NET.Test.Sdk"; version = "17.9.0"; hash = "sha256-q/1AJ7eNlk02wvN76qvjl2xBx5iJ+h5ssiE/4akLmtI="; })
  (fetchNuGet { pname = "Microsoft.TestPlatform.ObjectModel"; version = "17.9.0"; hash = "sha256-iiXUFzpvT8OWdzMj9FGJDqanwHx40s1TXVY9l3ii+s0="; })
  (fetchNuGet { pname = "Microsoft.TestPlatform.TestHost"; version = "17.9.0"; hash = "sha256-1BZIY1z+C9TROgdTV/tq4zsPy7Q71GQksr/LoMKAzqU="; })
  (fetchNuGet { pname = "Newtonsoft.Json"; version = "13.0.1"; hash = "sha256-K2tSVW4n4beRPzPu3rlVaBEMdGvWSv/3Q1fxaDh4Mjo="; })
  (fetchNuGet { pname = "System.Reflection.Metadata"; version = "1.6.0"; hash = "sha256-JJfgaPav7UfEh4yRAQdGhLZF1brr0tUWPl6qmfNWq/E="; })
  (fetchNuGet { pname = "xunit.abstractions"; version = "2.0.3"; hash = "sha256-0D1y/C34iARI96gb3bAOG8tcGPMjx+fMabTPpydGlAM="; })
  (fetchNuGet { pname = "xunit.analyzers"; version = "1.13.0"; hash = "sha256-K8cGR9+MdJknNPjlPbxQ1GhzXG+fK466jCfYxMwCK10="; })
  (fetchNuGet { pname = "xunit.assert.source"; version = "2.8.0"; hash = "sha256-RKQjfIIVpSIaEPmnyN/lBAwK29Vti6ppRNVRNMbCP1Q="; })
  (fetchNuGet { pname = "xunit.core"; version = "2.8.0"; hash = "sha256-nzHNl/fnEGsTSpkCrfGqEaqw4fUV+JZEmQ3B7g5I394="; })
  (fetchNuGet { pname = "xunit.extensibility.core"; version = "2.8.0"; hash = "sha256-0p5ywaDIlfoD2xf9irimlgpHPtY9fr+vJWptwHePqPY="; })
  (fetchNuGet { pname = "xunit.extensibility.execution"; version = "2.8.0"; hash = "sha256-I/duyJVsnXwR+ILpT+cvj/kjqlngAqvtZP/Hjie8OF0="; })
  (fetchNuGet { pname = "xunit.runner.visualstudio"; version = "2.8.0"; hash = "sha256-pZzKEO3zMO/kgPQ6UuWcBJZUzccs/sTnFp8ClQDad2c="; })
]
